title: Word AMU
description: feuille de style Microsoft Word pour les thèses soutenues à Aix-Marseille Université
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
